config/routes.rb
Blog::Engine.routes.draw do
  resources :articles
  root to: "articles#index"
end

app/models/blog/article.rb
module Blog
  class Article < ActiveRecord::Base
  end
end

app/controllers/blog/application_controller.rb
module Blog
  class ApplicationController < ActionController::Base
  end
end

app/controllers/blog/articles_controller.rb
require_dependency "blog/application_controller"

module Blog
  class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]

    # GET /articles
    def index
      @articles = Article.all
    end

    # GET /articles/1
    def show
    end

    # GET /articles/new
    def new
      @article = Article.new
    end

    # GET /articles/1/edit
    def edit
    end

    # POST /articles
    def create
      @article = Article.new(article_params)

      if @article.save
        redirect_to @article, notice: 'Article was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /articles/1
    def update
      if @article.update(article_params)
        redirect_to @article, notice: 'Article was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /articles/1
    def destroy
      @article.destroy
      redirect_to articles_url, notice: 'Article was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_article
        @article = Article.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def article_params
        params.require(:article).permit(:title, :body)
      end
  end
end

app/helpers/blog/application_helper.rb
module Blog
  module ApplicationHelper
    include FontAwesome::Rails::IconHelper

    def markdown(text, options={})
      renderer = Redcarpet::Render::HTML.new()
      markdown_renderer = Redcarpet::Markdown.new(renderer, extensions = {})
      # options = {downgrade: n} Downgrade Markdown heading by n levels for better rendering in the context of the page
      markdown_renderer.render(options.key?(:downgrade) ? text.gsub(/(#)+/, '\&###') : text).html_safe
    end

  end
end

app/helpers/blog/articles_helper.rb
module Blog
  module ArticlesHelper
  end
end

app/views/blog/articles/_form.html.haml
= form_for(@article) do |f|
  - if @article.errors.any?
    #error_explanation
      %h2
        = pluralize(@article.errors.count, "error")
        prohibited this article from being saved:
      %ul
        - @article.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :body
    = f.text_area :body, class: 'form-control', rows: 12
  .actions
    = f.submit nil, class: 'btn btn-primary'

app/views/blog/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/blog/articles/index.html.haml
%h3#all-articles All Articles

- @articles.each do |article|
  .article
    .article-date= article.created_at.strftime("%d %B %Y")
    %h3= link_to article.title, article
    %p= markdown(truncate(article.body, length: 800, separator: ' '){link_to 'Continue Reading', article_path(article)}, downgrade: 3)

app/views/blog/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/blog/articles/show.html.haml
%p#notice= notice
%h2= @article.title
%p= markdown(@article.body, downgrade: 3)
= link_to 'Edit', edit_article_path(@article)
|
= link_to 'Back', articles_path

app/views/layouts/blog/_author_side.html.haml
.author-side
  %h2#blog-title
    =link_to Blog::APP_CONFIG['blog']['title'], root_path
  =image_tag Blog::APP_CONFIG['author']['img'], id: 'author-img'
  %h2= Blog::APP_CONFIG['author']['name']
  %p.justified= Blog::APP_CONFIG['author']['biography']
  %ul#author-side-links
    %a
      %li
        = fa_icon "envelope-square"
        = link_to 'Email', "mailto:#{Blog::APP_CONFIG['author']['email']}"
    %a
      %li
        = fa_icon "github-square"
        = link_to 'Github', "https://github.com/#{Blog::APP_CONFIG['author']['github']}"
    %a
      %li
        = fa_icon "stack-overflow"
        = link_to 'Stack Overflow', "http://stackoverflow.com/users/#{Blog::APP_CONFIG['author']['stack-overflow']}"
    %a
      %li
        = fa_icon "industry"
        = link_to 'CV', Blog::APP_CONFIG['author']['cv_link']

app/views/layouts/blog/_footer.html.haml
%div#footer
  © 2015
  = link_to 'Bertrand Caron', 'https://bcaron.me'
  \. Powered by
  = link_to 'Ruby on Rails', 'http://rubyonrails.org'
  using the
  = link_to 'rails-blog', 'https://rubygems.org/gems/rails-blog'
  gem.

app/views/layouts/blog/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "blog/application", media: "all" %>
  <%= javascript_include_tag "blog/application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render file: 'layouts/blog/_author_side' %>

  <div id="index">
    <p id='blog-description'><%= Blog::APP_CONFIG['blog']['description'] %></p>
    <%= yield %>

    <%= render file: 'layouts/blog/_footer' %>
  </div>
</body>

</html>